# NumPy Fundamentals — Task 13

This notebook is your practice arena. You already know the theory; now you will apply it. Twenty questions below test the NumPy skills from Session 13: array creation, shapes, indexing, slicing, broadcasting, reductions, and a little functional thinking.

A note on how to work through these problems: in data science, knowing how to search for documentation is as valuable as knowing the syntax. If a question is unfamiliar, google it — search terms like 'numpy create null vector' or 'numpy softmax' will point you to Stack Overflow, the official docs, and blog posts. Reading those explanations is part of the learning process. Try to solve each question yourself first; when you are truly stuck, look at the solution notebook 
for that number.

Here is the ground you will cover:

- Questions 1-6 and 20 build and manipulate arrays: null vectors, random matrices, border arrays, identity matrices, and repeat/tile patterns.
- Questions 7-9 use arithmetic, reshaping, and dtype conversion: Euclidean distances, unraveling flat indexes, and reversing arrays with a new type.
- Questions 10-13 introduce functions over arrays: counting elements, softmax, vertical stacking, and working with dates via `datetime64`.
- Questions 14-18 are broadcasting and indexing challenges: subtracting row means, swapping columns, replacing odds, elementwise maximum, and normalisation.
- Question 19 closes with sorting into ranked positions.

A practical word on approach: read a question, write a first attempt even if you are unsure, run it, and then compare with the reference. Your failed attempts are not wasted time — they are what make the correct pattern memorable. When stuck, write down the shape you expect at each step; most beginner mistakes here are shape mistakes, and printing `.shape` is the fastest debugger you have. Keep answers short and vectorised; the moment a loop feels necessary, ask which NumPy function removes it. Good luck, and do not forget that googling is a legitimate superpower.

In [ ]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



## 1.1 Hint — Q1: Null vector

A 'null vector' here means an array of ten elements, all empty by default, with a single 1 placed in the fifth position. Remember that NumPy indexing starts at zero, so position five is index 4. Two routes work: start from `np.zeros(10)` and set `a[4] = 1`, or start from `np.nan * np.empty(10)` so the unpopulated cells print as NaN (not-a-number). The second route is closer to the reference solution and is a nice way to visualise which slots are still missing.

In [ ]:
#Code here

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

## 2.1 Hint — Q2: Random array from user input

This question mixes normal Python I/O with NumPy. First read two integers from one line using `a, b = map(int, input().split())`. Then build a matrix of the requested shape with `np.random.random((a, b))`, which fills every cell with a uniform random float between 0 and 1. Finally, print the array and compute the average — the simplest correct average is `x.mean()`, which reduces the whole array to one number without any axis argument.

In [ ]:
#Code here

###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

## 3.1 Hint — Q3: Border array

The border array is a classic NumPy trick: build a solid block of 1s with `np.ones((a, b))`, then overwrite everything except the border with 0. The interior is selected by the slice `x[1:-1, 1:-1]` — every row from 1 to the second-last, and every column from 1 to the second-last. Assigning 0 to that whole sub-block keeps only the ring of ones on the outer edge. Wrap this in a function that takes `(a, b)` as its shape parameters.

In [ ]:
#Code here

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


## 4.1 Hint — Q4: Values between 0 and 1

You need ten evenly spaced values strictly between 0 and 1. `np.linspace(0, 1, 10)` gives ten points including both endpoints, which is one short — including them makes the endpoints 0 and 1 themselves. The classic fix is to request twelve points and then drop the first and last with a slice: `np.linspace(0, 1, 12)[1:-1]`. That leaves exactly ten interior values. linspace is count-based, so choose the count and trim to taste.

In [ ]:
#Code here

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

## 5.1 Hint — Q5: Identity matrix of shape (3,4)

An identity matrix must be square: every diagonal entry is 1, every off-diagonal entry is 0, and only square matrices can satisfy that pattern. A (3,4) identity therefore does not exist. The right move is to explain why and then show `np.eye(3)` or `np.identity(3)` — the two functions are equivalent, with `np.eye` additionally supporting rectangular shapes with an offset diagonal via its `k` parameter.

In [ ]:
#Code here

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

## 6.1 Hint — Q6: Rows 0 to 4 in a 5x5 matrix

Every row should read `0 1 2 3 4`. Start from `np.zeros((5, 5))`. Then add the 1D vector `np.arange(5)` to the whole matrix; broadcasting stretches that single row across all five rows automatically. The expression `z += np.arange(5)` is enough — no explicit loop, no `tile`, just the fact that a size-5 vector aligns with the last axis of a (5,5) array.

In [ ]:
#Code here

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3]) 
```


## 7.1 Hint — Q7: Distance from a point

The words 'coordinates' and 'distance' should immediately suggest broadcasting plus a reduction. Generate ten random integer points in 2D with `np.random.randint(1, 100, (10, 2))`. Subtract the given point `np.array([2, 3])` — the single point broadcasts against every row. Square the differences, sum along `axis=1` to collapse the two coordinates, take `np.sqrt`, and finally cast the result to integer with `.astype(int)` because the question demands an integer distance array.

In [ ]:
#code here

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

## 8.1 Hint — Q8: Index of the 100th element

Given the shape (6,7,8), you are locating where the 100th element sits once the array is flattened in C order. The one-call answer is `np.unravel_index(100, (6, 7, 8))`, which converts a flat position back into multi-dimensional coordinates. Verify by hand: the last axis has size 8, then 7, then 6, so 100 = 1*56 + 5*8 + 4, giving (1, 5, 4). `unravel_index` and its inverse `ravel_multi_index` are the bridge between flat and n-dimensional views.

In [ ]:
#Code here

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

## 9.1 Hint — Q9: Reversed float array

The input arrives as one line of space-separated numbers, so first split it with `input().strip().split()`. Reverse the resulting Python list using `[::-1]`, then convert to a NumPy float array with `np.array(..., dtype=np.float32)` (or plain `float`/`float64`). The reversal is a plain Python slice trick; the dtype argument is what satisfies the 'element type float' requirement. For input `1 2 3 4 -8 -10` this yields `[-10.  -8.   4.   3.   2.   1.]`.

In [ ]:
#Code here

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

## 10.1 Hint — Q10: Element count

The total number of elements is not the length of the first axis but the product of all dimensions. A 1D array of two numbers has 2 elements; a (2,3) array has 6. The `.size` attribute computes this product for any shape, which is why the reference uses `a.size` — empty arrays report 0, simple vectors report their length, and higher-dimensional arrays report the full product.

In [ ]:
#Code here

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01, 
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

## 11.1 Hint — Q11: Softmax

Softmax converts a vector of real numbers into probabilities that sum to 1: each output is `exp(z_i) / sum(exp(z_j))`. The function should validate its input first — require an exact `np.ndarray` type and a 1D shape, raising `TypeError` otherwise. Then compute `s = np.sum(np.exp(arr))` and return `np.exp(arr) / s`. The tiny probabilities near zero in the examples are expected: exponentials of negative inputs produce vanishingly small values.

In [ ]:
#Code here

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]] 
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

## 12.1 Hint — Q12: Vertical stacking

This question is about variadic design plus a single NumPy call. Define the function with `*args` so it accepts any number of arrays. Loop over the arguments and reject anything that is not an `np.ndarray` by raising `TypeError`. Finally return `np.vstack(args)`, which piles the arrays top to bottom along axis 0 — every input must share the same number of columns. The examples show two and then three matrices stacking cleanly.

In [ ]:
#Coder here

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

## 13.1 Hint — Q13: Date arrays

The trick is that `np.arange(start, end, dtype='datetime64[D]')` excludes the end date, but the problem includes it. So first advance the supplied end by one day (handling the month rollover when the day would exceed the month's length), then let `arange` generate the full inclusive range. The reference solution parses the end string, increments the day, and uses a small dictionary of days per month to fix up month boundaries before calling `arange`.

In [ ]:
#Code here

###`Q-14:` Subtract the mean of each row from a matrix.

## 14.1 Hint — Q14: Subtract row mean

Subtract each row's own mean from every element in that row. Compute the per-row means with `x.mean(axis=1, keepdims=True)` — the `keepdims=True` is essential because it preserves the shape (5,1) so the means broadcast correctly across the columns. Then one subtraction `x - x.mean(axis=1, keepdims=True)` does the whole job. Without keepdims, shape (5,) would broadcast against columns instead of rows and silently produce the wrong result.

In [ ]:
#code here

###`Q-15:` Swap column-1 of array with column-2 in the array.

## 15.1 Hint — Q15: Swap columns 1 and 2

Swapping two columns is a one-line fancy-indexing operation: pass the new column order as a list. For a (3,3) array, `a[:, [0, 2, 1]]` returns an array whose first column is unchanged and whose second and third columns are exchanged. No temporary variable, no loop — the index list simply restates the desired column layout, and NumPy gathers the data accordingly.

In [ ]:
#Code here

###`Q-16:` Replace odd elements in arrays with -1.

## 16.1 Hint — Q16: Replace odd elements

Use a boolean mask: the expression `a % 2 == 1` is True exactly where elements are odd. Placing that mask on the left of an assignment — `a[a % 2 == 1] = -1` — writes -1 into precisely those positions. This is boolean indexing in assignment mode: the mask selects, and the right-hand side fills. The result turns `[0 1 2 3 ... 9]` into `[0 -1 2 -1 4 -1 ...]`.

In [ ]:
#Code here

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
``` 

## 17.1 Hint — Q17: Pairwise maximum

The task is to build, at every position, the larger of the two input values. The idiomatic one-liner is `np.maximum(a, b)`, which compares elementwise and returns the greater. The reference solution shows a fancier boolean-mask route: `a[b > a] = b[a < b]` copies the larger entry into `a` wherever `b` wins. Either approach yields `[6 3 1 7 8]` for the example.

In [ ]:
#Code here

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [ ]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[2939, 1694, 6680, 8865, 2684],
       [4066, 4573,  327, 6525,  851],
       [5997, 7481, 2315, 5863, 9615],
       [7821, 1225, 9138, 1114, 4885],
       [7715, 8046, 9105, 3935, 3182],
       [8842, 4836, 2705, 3751, 3800],
       [4132, 1400, 7844, 9471, 7526],
       [2749, 2624, 6900, 1576, 7515]])

## 18.1 Hint — Q18: Alternate columns and normalise

Two independent tasks sit in this question. First, fetch every alternate column: the slice `arr1[:, ::2]` keeps columns 0, 2, and 4 (start at the beginning, step by 2). Second, apply min-max normalisation with the formula `(X - X.min()) / (X.max() - X.min())` — here `arr1.min()` and `arr1.max()` without an axis produce the global minimum and maximum, rescaling every value into the range [0, 1].

In [ ]:
#Code here

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

## 19.1 Hint — Q19: nth largest

Sort the array and index from the end. After sorting ascending, `arr[-1]` is the largest, `arr[-2]` the second largest, and in general `arr[-n]` is the n-th largest. Guard against `n > len(arr)` by raising an error, then return `arr[-n]`. Remember that `arr.sort()` sorts in place — use `np.sort(arr)` when you want to keep the original order.

In [ ]:
#Code here

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

## 20.1 Hint — Q20: Repeat and tile pattern

The target splits naturally into two halves. The first half, `1 1 1 2 2 2 3 3 3`, repeats each element of the input — that is `np.repeat(a, 3)`. The second half, `1 2 3 1 2 3 1 2 3`, repeats the whole array — that is `np.tile(a, 3)`. Join the two with `np.hstack([np.repeat(a, 3), np.tile(a, 3)])`. Keep the pattern parameterised by the input array; no hardcoding allowed.

## Summary

Task 13 put the Session 13 fundamentals to work across twenty small problems. You created and shaped arrays with generators like `np.arange`, `np.linspace`, `np.ones`, `np.zeros`, and `np.random`, and learned tiny slice tricks such as `[1:-1]` to trim endpoints. Broadcasting appeared in row-tiled matrices, distances, and row-mean subtraction. You validated function inputs for softmax and variadic stacking, reversed and re-typed arrays for output, and mapped flat indices back into n-dimensional coordinates with `unravel_index`. Later problems exercised boolean masks, pairwise maxima, min-max normalisation, sorting for ranks, and repeat-versus-tile patterns. If any solution still feels strained, re-read the fitting Session 13 section — every answer here is held together by shapes and axes.

In [ ]:
#code here