# NumPy Function Toolkit — Task 15

This task set turns the Session 15 function menu into nine matching problems. Every question is built around one or two functions from the tour — `np.sort`, `np.append`/`np.concatenate`, `np.unique`, `np.flip`, masking plus `np.where`, flattening, `np.clip`, and percentiles. Solving them is the best way to convert the function list in your head into working memory.

A realistic strategy: read the function menu once, then attempt each question using only the names you remember. The act of recalling whether you need `argsort` versus `sort`, or `tile` versus `repeat`, is exactly the learning this session is meant to produce. When you are stuck, google the function name together with the goal — for example 'numpy argsort sort by column' — and compare your approach with the reference solution.

Here is what awaits:

- Q1 is a four-way sort: plain `np.sort`, sorting rows by the 2nd column, sorting rows by their maximum, and sorting by overall element values.
- Q2 mimics a real data chore: adding a subject column, appending two student records, computing a totals column, and sorting descending to show the top rows.
- Q3 uses the `axis` parameter of `np.unique` to find unique rows and unique columns.
- Q4 flips a matrix along both axes at once with `np.flip`.
- Q5 detects which rows contain an element above a threshold using a boolean reduction plus `np.where`.
- Q6 joins several 1D arrays into one flat array.
- Q7 locates and deletes the minimum and maximum of a seeded random array.
- Q8 clips, sorts, and cumulatively sums an array in one chained expression.
- Q9 rounds an array and cross-checks percentile identities against min and max.

Work down the list in order; each problem reinforces the previous ones. You are allowed — even encouraged — to look things up, but write the final code yourself, and run it to confirm the shapes and values are right. Let's see how well the function tour sticks.

###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr = 
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

## 1.1 Hint — Q1: Four kinds of sort

Create a random `(4, 3)` matrix first, then answer four different questions:

- `np.sort(arr)` sorts each row's values in ascending order (the default axis is the last one).
- Sorting by column 2 means reordering whole rows so that column's values increase — use `np.argsort`: `arr[arr[:, 1].argsort()]`.
- Sorting by each row's maximum means the key is `max(row)`; `sorted(arr, key=lambda x: max(x))` achieves it, or compute `np.argsort(arr.max(axis=1))` and index.
- 'Sort based on elements value' flattens everything: `np.sort(arr, axis=None).reshape(4, 3)` sorts all twelve numbers then restores the matrix shape.

Compare each output with the worked example to confirm you chose the right axis.

In [ ]:
# code here

###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

## 2.1 Hint — Q2: Growing and ranking a marks table

Treat this as a small pipeline of concatenations:

- Add the extra subject as a new column: reshape `extra_subject` to `(5, 1)` with `.reshape(-1, 1)` and `np.concatenate([marks, extra_subject], axis=1)`.
- Add the two new students as rows: reshape each record to `(1, 5)` with `.reshape(1, -1)` and concatenate on `axis=0`.
- Add a totals column: `marks.sum(axis=1, keepdims=True)` keeps the shape `(n, 1)` so it joins on `axis=1`.
- Finally sort descending by the last column: `sorted` with `key=lambda x: x[-1]` and `reverse=True` (or `argsort` with `[::-1]`).

The note about 'changing dimension during concatenation' is deliberately hinting at the reshape calls — mismatched shapes are the usual failure point.

In [ ]:
# code here

###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

## 3.1 Hint — Q3: Unique rows and columns

The `axis` parameter changes what `np.unique` considers a 'value':

- `np.unique(arr, axis=0)` treats each row as a unit and returns the distinct rows, sorted.
- `np.unique(arr, axis=1)` treats each column as a unit and returns the distinct columns.

For the given 4x6 array, rows 0 and 3 are identical, so the row-wise result has 3 rows; column-wise, one column is a duplicate, so the result has 5 columns. No manual comparisons needed — the function decides uniqueness.

In [ ]:
# code here

###`Q-4:` Flip given 2-D array along both axes at the same time.

## 4.1 Hint — Q4: Flip both axes

Flipping along both axes reverses the row order and the column order at the same time — the array equivalent of a 180-degree rotation. `np.flip(arr, axis=[0, 1])` flips rows (axis 0) and columns (axis 1) together, and the shape is preserved. If you flip twice you get the original back, which is a nice sanity check.

In [ ]:
# code here

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5], 
      [10,-3,30,4,5], 
      [3,2,5,-4,5], 
      [9,7,3,6,5]] 

X = 6
```

## 5.1 Hint — Q5: Rows with an element larger than X

Combine a boolean test with a reduction:

- `arr > X` produces a same-shape boolean matrix.
- `np.any(arr > X, axis=1)` collapses each row to True if any element exceeds X — row-level 'any'.
- `np.where(condition)` returns the indices where the condition is True, i.e. the matching row numbers.

For the sample array the rows with a value above 6 are row 1 and row 3. Observe that it is `any` over rows, not `all`.

In [ ]:
# code here

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [ ]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

## 6.1 Hint — Q6: Flatten several arrays

Joining a few 1D arrays into one flat 1D array is exactly what `np.concatenate` does on the default axis: `np.concatenate([arr1, arr2, arr3])` yields `[0 1 2 3 4 5 6 7 8 9]`. Alternatives include `np.hstack([arr1, arr2, arr3])` and `np.r_[arr1, arr2, arr3]`. The arrays are already 1D, so no reshaping is required before the join.

In [1]:
# code here

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

## 7.1 Hint — Q7: Remove min and max

The array is `(1, 200)`, so find the extremes and delete them along the width direction:

- `arr.argmax()` and `arr.argmin()` give the flat positions of the largest and smallest elements.
- `np.delete(arr, index, axis=1)` removes the element at that position; delete the max first, then recompute the min position before deleting — deletion shifts the array.
- Reproduce determinism by calling `np.random.seed(400)` before creating the array, exactly as given.

In [ ]:
# code here

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

## 8.1 Hint — Q8: Clip, sort, cumulative sum

Chain three Session 15 functions in one expression:

- `np.clip(arr, 100, 200)` pushes every value into the range [100, 200] — below 100 becomes 100, above 200 becomes 200.
- `np.sort(...)` sorts the clipped values ascending.
- `np.cumsum(...)` produces the running total.

Written as `np.cumsum(np.sort(np.clip(arr, 100, 200)))`, the output reads right to left: clip, then sort, then accumulate. Confirm how many values sat below 100 by checking how long the cumsum starts at 100 in a row.

In [ ]:
# code here

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

## 9.1 Hint — Q9: Percentile identities

Start with an array in [0, 1], round it to three decimals with `np.around(arr, decimals=3)`, then verify four facts:

- `np.percentile(arr, 0)` equals `arr.min()` — the smallest value is at percentile zero by definition.
- `np.percentile(arr, 100)` equals `arr.max()`.
- `np.percentile(arr, 50)` is the median.
- The difference `np.percentile(arr, 51) - np.percentile(arr, 50)` measures how much the value climbs in the 0.01 of the distribution around the median; with 100 rounded points each percentile step is roughly one index apart.

Print each comparison to confirm the expectations.

## Summary

Task 15 exercised the Session 15 function toolkit end to end. You sorted a matrix four different ways — within rows, by a key column with `argsort`, by row maxima, and globally via `axis=None` — then built a realistic marks pipeline with `np.concatenate` and `reshape(-1, 1)`/`reshape(1, -1)`, added a totals column, and ranked students descending. You used the `axis` argument of `np.unique` to isolate distinct rows and columns, mirrored an array with `np.flip`, and detected threshold-crossing rows with `np.any` plus `np.where`. Flattening came from a simple `np.concatenate`, extreme deletion from `np.delete` on a seeded array, and one chained expression handled clip-sort-cumsum. Finally, percentile identities were verified against min, max, and a tiny median gap. If a question needed more than a few lines, re-check which single function would have collapsed it — that awareness is the session's real prize.

In [ ]:
# code here